# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-22 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeAcopio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('centro', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('urgencia', models.CharField(max_length=10)),
                ('brigadistas', models.CharField(max_length=2)),
                ('contacto', models.CharField(max_length=200)),
                ('telefono', models.IntegerField(default=0)),
                ('viveres', models.CharField(max_length=5000)),
                ('medicamentos', models.CharField(max_length=5000)),
                ('herramientas', models.CharField(max_length=5000)),
                ('ubicacion', models.CharField(max_length=1000)),
                ('infoAdicional', models.CharField(max_length=2000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
